# Generated by Django 6.0.2 on 2026-04-23 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilechangetoken_token_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.CharField(choices=[('password_reset_requested', 'Password Reset Requested'), ('password_reset_confirmed', 'Password Reset Confirmed')], db_index=True, max_length=64)),
                ('result', models.CharField(choices=[('email_sent', 'Email Sent'), ('no_user', 'No User'), ('email_send_failed', 'Email Send Failed'), ('success', 'Success'), ('token_not_found', 'Token Not Found'), ('token_already_used', 'Token Already Used'), ('invalid_secret', 'Invalid Secret'), ('token_expired', 'Token Expired'), ('weak_password', 'Weak Password')], max_length=32)),
                ('email_hash', models.CharField(blank=True, default='', max_length=32)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'result'], name='users_audit_event_e090f8_idx'), models.Index(fields=['-created_at'], name='users_audit_created_3a5128_idx')],
            },
        ),
    ]
