# Generated by Django 6.0.2 on 2026-04-23 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilechangetoken',
            name='token_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='profilechangetoken',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilechangetoken',
            name='change_type',
            field=models.CharField(choices=[('email', 'Email'), ('email_new', 'Email New'), ('password', 'Password'), ('verify', 'Verify'), ('2fa_login', '2FA Login'), ('password_reset', 'Password Reset')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='profilechangetoken',
            index=models.Index(fields=['user', 'change_type'], name='users_profi_user_id_11da22_idx'),
        ),
    ]
