# Generated by Django 6.0.2 on 2026-04-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechangetoken',
            name='new_value',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
