# Generated by Django 6.0.2 on 2026-05-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_totp_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechangetoken',
            name='change_type',
            field=models.CharField(choices=[('email', 'Email'), ('email_new', 'Email New'), ('password', 'Password'), ('verify', 'Verify'), ('2fa_login', '2FA Login'), ('password_reset', 'Password Reset'), ('totp_pending', 'TOTP Pending Login'), ('totp_setup_pending', 'TOTP Setup Pending')], max_length=20),
        ),
    ]
