# Generated by Django 6.0.2 on 2026-06-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profilechangetoken_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consent_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
