# Generated by Django 6.0.2 on 2026-06-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_consent_fields_to_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event',
            field=models.CharField(choices=[('password_reset_requested', 'Password Reset Requested'), ('password_reset_confirmed', 'Password Reset Confirmed'), ('account_deleted', 'Account Deleted')], db_index=True, max_length=64),
        ),
    ]
