# Generated by Django 6.0.2 on 2026-06-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_account_deleted_to_auditlog_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='checksum',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='event',
            field=models.CharField(choices=[('password_reset_requested', 'Password Reset Requested'), ('password_reset_confirmed', 'Password Reset Confirmed'), ('account_deleted', 'Account Deleted'), ('login_failed', 'Login Failed'), ('totp_login_success', 'TOTP Login Success'), ('totp_login_failed', 'TOTP Login Failed'), ('totp_setup_complete', 'TOTP Setup Complete')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='result',
            field=models.CharField(choices=[('email_sent', 'Email Sent'), ('no_user', 'No User'), ('email_send_failed', 'Email Send Failed'), ('success', 'Success'), ('token_not_found', 'Token Not Found'), ('token_already_used', 'Token Already Used'), ('invalid_secret', 'Invalid Secret'), ('token_expired', 'Token Expired'), ('weak_password', 'Weak Password'), ('invalid_credentials', 'Invalid Credentials'), ('failed', 'Failed')], max_length=32),
        ),
    ]
